name: Validate Python e2e

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 30 3 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-versions-from-manifest:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
        python: [3.9.13, 3.10.11, 3.11.9, 3.12.3, 3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./
        with:
          python-version: ${{ matrix.python }}

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          $pythonVersion = (python --version)
          if ("Python $env:MATRIX_PYTHON" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is $env:MATRIX_PYTHON"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-versions-from-file:
    name: Setup ${{ matrix.python }} ${{ matrix.os }} version file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
        python: [3.9.13, 3.10.11, 3.11.9, 3.12.3, 3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: build-version-file ${{ matrix.python }}
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: echo "$MATRIX_PYTHON" > .python-version

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./
        with:
          python-version-file: .python-version

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          $pythonVersion = (python --version)
          if ("Python $env:MATRIX_PYTHON" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is $env:MATRIX_PYTHON"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-versions-from-file-without-parameter:
    name: Setup ${{ matrix.python }} ${{ matrix.os }} version file without parameter
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
        python: [3.9.13, 3.10.11, 3.11.9, 3.12.3, 3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: build-version-file ${{ matrix.python }}
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: echo "$MATRIX_PYTHON" > .python-version

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          $pythonVersion = (python --version)
          if ("Python $env:MATRIX_PYTHON" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is $env:MATRIX_PYTHON"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-versions-from-standard-pyproject-file:
    name: Setup ${{ matrix.python }} ${{ matrix.os }} standard pyproject file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
        python: [3.9.13, 3.10.11, 3.11.9, '==3.12.3', 3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: build-version-file ${{ matrix.python }}
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          echo '[project]
            requires-python = "'"$MATRIX_PYTHON"'"
          ' > pyproject.toml

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./
        with:
          python-version-file: pyproject.toml

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          $pythonVersion = (python --version)
          if ("Python $env:MATRIX_PYTHON".replace("==", "") -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is $env:MATRIX_PYTHON"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-versions-from-poetry-pyproject-file:
    name: Setup ${{ matrix.python }} ${{ matrix.os }} poetry pyproject file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
        python: [3.9.13, 3.10.11, 3.11.9, 3.12.3, 3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: build-version-file ${{ matrix.python }}
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          echo '[tool.poetry.dependencies]
            python = "'"$MATRIX_PYTHON"'"
          ' > pyproject.toml

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./
        with:
          python-version-file: pyproject.toml

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          MATRIX_PYTHON: ${{ matrix.python }}
        run: |
          $pythonVersion = (python --version)
          if ("Python $env:MATRIX_PYTHON" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is $env:MATRIX_PYTHON"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-pre-release-version-from-manifest:
    name: Setup 3.14.0-alpha.1 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: setup-python 3.14.0-alpha.1
        id: setup-python
        uses: ./
        with:
          python-version: '3.14.0-alpha.1'

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        run: |
          $pythonVersion = (python --version)
          if ("Python 3.14.0a1" -ne "$pythonVersion"){
            Write-Host "The current version is $pythonVersion; expected version is 3.14.0a1"
            exit 1
          }
          $pythonVersion
        shell: pwsh

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-dev-version:
    name: Setup 3.14-dev ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, macos-13]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: setup-python 3.14-dev
        id: setup-python
        uses: ./
        with:
          python-version: '3.14-dev'

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          PYTHON_VERSION: ${{ steps.setup-python.outputs.python-version }}
        run: |
          case "$PYTHON_VERSION" in
            3.14.*) ;;
            *) echo "Unexpected python version: $PYTHON_VERSION"; exit 1 ;;
          esac
        shell: bash

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-prerelease-version:
    name: Setup 3.14 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, macos-13]
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: setup-python 3.14
        id: setup-python
        uses: ./
        with:
          python-version: '3.14'
          allow-prereleases: true

      - name: Check python-path
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: ./__tests__/check-python-path.sh "$PYTHON_PATH"
        shell: bash

      - name: Validate version
        env:
          PYTHON_VERSION: ${{ steps.setup-python.outputs.python-version }}
        run: |
          case "$PYTHON_VERSION" in
            3.14.*) ;;
            *) echo "Unexpected python version: $PYTHON_VERSION"; exit 1 ;;
          esac
        shell: bash

      - name: Run simple code
        run: python -c 'import math; print(math.factorial(5))'

  setup-versions-noenv:
    name: Setup ${{ matrix.python }} ${{ matrix.os }} (noenv)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            macos-latest,
            windows-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            macos-13,
            ubuntu-latest
          ]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: setup-python ${{ matrix.python }}
        id: setup-python
        uses: ./
        with:
          python-version: ${{ matrix.python }}
          update-environment: false

      - name: Python version
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: "$PYTHON_PATH" --version

      - name: Run simple code
        env:
          PYTHON_PATH: ${{ steps.setup-python.outputs.python-path }}
        run: "$PYTHON_PATH" -c 'import math; print(math.factorial(5))'

  check-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Setup Python and check latest
        uses: ./
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Validate version
        env:
          MATRIX_PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          $pythonVersion = (python --version)
          if ("$pythonVersion" -NotMatch "$env:MATRIX_PYTHON_VERSION"){
            Write-Host "The current version is $pythonVersion; expected version is $env:MATRIX_PYTHON_VERSION"
            exit 1
          }
          $pythonVersion
        shell: pwsh

  setup-python-multiple-python-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Setup Python and check latest
        uses: ./
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12
            3.13
          check-latest: true
      - name: Validate version
        run: |
          $pythonVersion = (python --version)
          if ("$pythonVersion" -NotMatch "3.13"){
            Write-Host "The current version is $pythonVersion; expected version is 3.13"
            exit 1
          }
          $pythonVersion
        shell: pwsh
